_wandb:
    value:
        cli_version: 0.25.1
        e:
            amqhvcj11g4smgkidqtnr3de3vbl1xp0:
                args:
                    - -config_fn
                    - mnist
                codePath: src/main.py
                codePathLocal: src/main.py
                cpu_count: 48
                cpu_count_logical: 96
                cudaVersion: "13.1"
                disk:
                    /:
                        total: "4294967296"
                        used: "32768"
                email: 0322sagibenedek@gmail.com
                executable: /opt/conda/bin/python
                git:
                    commit: e5b42d81dbbf0bb546cf6a428f17551653a67a1c
                    remote: https://github.com/kemvagyok/GNN-Few-shot-classification.git
                gpu: Quadro RTX 6000
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 4608
                      memoryTotal: "25769803776"
                      name: Quadro RTX 6000
                      uuid: GPU-f5e81079-123c-2484-464b-1e6c65a55251
                host: vn01
                memory:
                    total: "269627396096"
                os: Linux-4.18.0-553.54.1.el8_10.x86_64-x86_64-with-glibc2.35
                program: /home/c_gnnsb2/workspace/src/main.py
                python: CPython 3.11.13
                root: /home/c_gnnsb2/workspace
                startedAt: "2026-03-24T20:03:07.834205Z"
                writerId: amqhvcj11g4smgkidqtnr3de3vbl1xp0
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 77
                - 100
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 77
                - 100
            "3":
                - 13
                - 16
            "4": 3.11.13
            "5": 0.25.1
            "6": 5.3.0
            "10":
                - 20
            "12": 0.25.1
            "13": linux-x86_64
K_hop:
    value: 1
K_neigh:
    value: 3
batch_size:
    value: 128
dataset:
    value: MNIST
epochs:
    value: 2500
is_ddp:
    value: false
lr_cnn:
    value: 0.01
lr_gcn:
    value: 0.01
max_label:
    value: 100
