paths:
  dataset_path: "./data"
  logs_path: "./logs"
  results_path: "./results"

dataset:
  dataset_name: "MNIST"  # "ISIC2019", "ChestX", "MNIST"
  train_images_per_class: [1, 2, 5, 10, 20, 50, 100]
  validation_size: 1200
  test_size: 4000
  use_minibatch: false
  without_valid: false

graph:
  K_neigh: 3
  K_hop_list: [1, 2, 3, 4, 5, 6]
  graph_refresh: 10
  rebuild_graph_each_epoch: true

training:
  embedding: "cnn" #cnn, resnet18
  gcn_model: "GAT" # GCN, GAT
  lr_embedder: 0.01
  lr_gcn: 0.01
  epochs_max: 2500
  batch_size: 128

similarity:
  # method_similar: "p_norm"
  # p_n_vectors: [1, 2, 3]

model:
  latens_size: 64

reproducibility:
  seed: 42