train_images_per_class = [1,2,5,10,20,50,100] # How many labeled images are in each classes.
validation_size = 1200
test_size = 1000
K_neigh = 3 #How many edges does have each nodes? (KNN)
K_hop = 3
lr = 0.01
method_similar = 'p_norm'
p_n_vectors = [1,2,3]
epochs_max = 2500
latens_size = 64
graph_refresh = 10 # Oszhatóság alapján újragenerálja a gráfot, hogy a tanulás során ne ragadjon bele egy helyi optimumba.