dataset:
  name: MNIST
  validation_size: 1200
  test_size: 1000
  train_images_per_class: [1, 2, 5, 10, 20, 50, 100]

graph:
  K_neigh: 3
  K_hop_list: [1, 2, 3, 4, 5, 6]
  graph_refresh: 10

training:
  lr: 0.01
  epochs_max: 2500
  seed: 42

model:
  latens_size: 64

similarity:
  method: p_norm
  p_n_vectors: [1, 2, 3]